#!/bin/bash

# A bash file to init the personal pade workspace


# Util variables and functions
run() {
	pade start-runtime $1
}

read -r -d '' help << EOT
NAME
       padex - runs some actions for PADE dev env

SYNOPSIS
       padex [FILE TO RUN]
       padex -r [FILE TO RUN]

DESCRIPTION
       Run some actions for the PADE development environment.

OPTIONS
       -r, --run
              Run the provided file with PADE.

       -h, --help
              Show the help.
EOT


# Activities of the script
case $1 in
	'-r' | '--run')
		run $2
		;;

	'-h' | '--help')
		echo "$help"
		;;

	*)
		if [[ -e $1 ]]; then
			run $1
		else
			echo 'File not found or unknown option. Use padex -h to see the help.'
		fi
		;;
esac
