#!/bin/bash

# A bash file to init the personal smash workspace


# Util variables and functions
run() {
	pade start-runtime $1
	#pade start-runtime $workspaces/smash-py/main.py
}

runtest() {
	if [[ $1 == "" ]]; then
		echo "No such argument provided. Please, provide a test system file to run smash."
	else
		pade start-runtime $1
	fi
}


read -r -d '' help << EOT
NAME
       smash - runs some actions for smash-py dev env

SYNOPSIS
       smash
       smash -r
       smash -r [FILE TO RUN]

DESCRIPTION
       Runs some actions for the smash-py development environment.

OPTIONS
       -r, --run
              Run the provided file with smash. This runs the main file of smash if no parameter is provided.

       -h, --help
              show the help
EOT


# Activities of the script
case $1 in
	'')
		run $workspaces/smash-py/main.py
		;;

	'-r' | '--run')
		if [[ $2 == "" ]]; then
			run $workspaces/smash-py/main.py
		else
			run $2
		fi
		;;

	'-h' | '--help')
		echo "$help"
		;;

	*)
		echo 'Unknown option. Use smash -h to see the help.'
		;;
esac
