#!/bin/sh
#
# A bash file that compiles some of the most common commands on Integration app
#

# Defining the jobs of the script

connect-aws(){
    read "?Input MFA Token: " TOKEN
    echo "Generating temp session credentials..."
    aws sts get-session-token --serial-number arn:aws:iam::701893420597:user/italo.campos --token-code ${TOKEN} > /tmp/aws-cli.json
    # aws sts get-session-token > /tmp/aws-cli.json
    export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' /tmp/aws-cli.json)
    export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' /tmp/aws-cli.json)
    export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' /tmp/aws-cli.json)
}

read -r -d '' help << EOT
LOGGI GENERAL TOOL

Description: Compiles genetal dev tools for Loggi's env.

Usage: tools <args>

Options:
    --conenct-aws
        Creates a temporary session to access the S3 bucket of Integration

    -h, --help
        Shows this help text.

Examples of usage:
    tools --connect-aws
    tools -h
EOT


# Selects the funcion to execute
case $1 in
    '--connect-aws')
        connect-aws
        ;;

    '' | '-h' | '--help')
        echo "$help"
        ;;

    *)
        echo 'Unknown option. Use tools -h to see the help.'
        ;;
esac
